### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by smythp** [overview/pdfocr#3]
Thanks for a great utility! When running pdfocr on a droplet, I'm getting "out of memory" errors. Is there a minimum amount of memory needed to run tessaract? Any flags or workarounds I can try to mitigate this? 

Thanks you!

**Comment by adamhooper** [comment]
I'm not sure what a droplet is. Here's what I do know.

First, let's talk components. Pdfocr parses PDFs using PDFBox, and then it sends the parsed stuff to Tesseract. PDFBox relies upon all sorts of image-processing libraries, such as a TIFF reader and a JPEG reader.

Some of those image-processing libraries can use an infinite amount of memory, depending on the input PDF. So right off the bat, you can't _solve_ out-of-memory errors; you can only try to mitigate them.

PDFBox lets you limit the amount of memory it uses on non-image parts of the page. We configure that limit here: https://github.com/overview/pdfocr/blob/master/src/main/scala/org/overviewproject/pdfocr/pdf/PdfDocument.scala#L82 ... as I understand it, PDFBox uses a "scratchpad" as it parses PDFs; anything above that limit will go to disk instead of RAM. So if you set the number lower, you'll use less memory and PDFBox will be slower.

As for Tesseract: I don't really understand everything it does. I suspect the amount of memory it uses is proportional to the size of the input image. So you can limit the amount of memory it uses by limiting the size of the image you send it. We hard-code a limit of 4000x4000 here: https://github.com/overview/pdfocr/blob/master/src/main/scala/org/overviewproject/pdfocr/pdf/PdfPage.scala#L34 ... if you change that to 2000x2000, I suspect the top possible amount of memory Tesseract uses will drop by 75%. (Tesseract will also operate faster, but more of its output will be OCR gibberish.)

So there are options.

The bad news is: I don't know whether editing either variable will actually work for _your PDF_. Maybe PDFBox and its libraries are using 400MB on your PDF; in that case, tweaking the PDFBox scratchpad limit from 50MB to 25MB would only save you a paltry 25MB. And maybe the images you're sending Tesseract are actually 800x800, in which case lowering the limit to 2000x2000 won't save you any memory at all.

Here are the three ways I'd proceed, in order:
1. Behave as though you'll never solve _all_ OutOfMemory errors. Pdfocr will fail on some inputs, because PDFBox does. The only way to avoid that is to switch away from PDFBox, which is difficult (and tempting).
   - If you're using Pdfocr as a library: OutOfMemory is tricky because you can't catch it (correctly). The solution is to run Pdfocr in a new process (like we do here: https://github.com/overview/overview-server/blob/master/worker/src/main/scala/com/overviewdocs/jobhandler/filegroup/task/PdfNormalizer.scala) ... but that'll spin up a second JVM, which costs more memory.
   - If you're invoking Pdfocr on the command line: always check the exit code. Errors will happen.
2. Try and figure out what's using memory. You can use `top` to see if it's PDFBox; you can use some Java tools (I'm a novice in this domain) to see whether it's the Java Heap; otherwise, maybe PDFBox's image-parsing libraries are using `malloc()` and/or `mmap()`. Once you know where the memory footprint is too high, try to mitigate it. (If it's Tesseract or PDFBox, tweak the files I mentioned above. If it's the image-parsing libraries, uh, I think you're doomed.)
3. Fake a higher-memory system by adding swap space. (This will slow Pdfocr down considerably.)

That's all I've got for you! I'd happily accept pull requests that check system properties for the PDFBox memory limit or the maximum image resolution.

Beyond that, a parting thought: OCR takes a lot of memory. Sure, Pdfocr could be a little leaner ... but not much. Conventional wisdom is: if you want to do OCR, buy RAM.

**Comment by smythp** [comment]
Thank you for taking the time to respond...this is an incredible resource. I don't really care if the OCR runs slowly as long as it eventually completes, so have started looking into allowing it to use swap when it runs out of memory. For the time being, I've upgraded the machine to 1 GB of memory, which seems to give abnormal output but pushes through to completion. That should do for the time being. Thanks again, and great work on this library which I use daily.
